### PR TITLE
Fix missing compatibility with CHART.JS version 2.x

### PR DESCRIPTION
**Pull request by stockiNail**
The PR # 16 introduced a breaking change, removing the support of version CHART.JS 2.x.
This PR is fixing it.

### CODE REVIEW

**Comment by kurkle** [comment]
I think a new helper would be good (to resolve the code smell too):

```js
const parse = Chart.version 
  ? (scale, value) => scale.parse(value) 
  : (scale, value) => value;

function scaleValue(scale, value) {
  const normValue = isNumber(value) ? parseFloat(value) : parse(scale, value);
  return scale.getPixelForValue(normValue);
}
``

**Comment by stockiNail** [comment]
> I think a new helper would be good (to resolve the code smell too):

I haven't seen your post. I do now.

**Comment by stockiNail** [comment]
de facto, this PR is not solving the compatibility with version 2 because it didn't work anyway, but, together with PR #18, it is solved.

**Review by kurkle — APPROVED** [review]

**Comment by stockiNail** [comment]
FYI, I have tested the master and now it works both 3.x and 2.x !!! :ok_hand: :satisfied:

**Pull request merged**
