### PR TITLE
Add test cases for time axis

### PR DESCRIPTION
**Pull request by stockiNail**
Add test cases for time axis, setting intl data in order to be sure the picture will be the same wherever the test is performed

### CODE REVIEW

**Comment by kurkle** [comment]
Your data range probably contains change in daylight saving? That could be the issue.

**Comment by stockiNail** [comment]
> Your data range probably contains change in daylight saving? That could be the issue.

I have changed the dates (using this week therefore without daylight saving in the middle) but it seems not related to that. Maybe I'm wrong

```console
            |Lines       |Functions  |Branches    
Filename    |Rate     Num|Rate    Num|Rate     Num
==================================================
src/index.js|87.0%     54|81.8%    11|    -      0
==================================================
      Total:|87.0%     54|81.8%    11|    -      0
(node:2224) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
src/index.js|87.0%     54|81.8%    11|    -      0 === test/fixtures/xCartesianTime.js
src/index.js|87.0%     54|81.8%    11|    -      0 === test/fixtures/xCartesianTime.png
src/index.js|87.0%     54|81.8%    11|    -      0 === test/fixtures/xCartesianTimeParsing.js
src/index.js|87.0%     54|81.8%    11|    -      0 === test/fixtures/xCartesianTimeParsing.png
src/index.js|87.0%     54|81.8%    11|    -      0 === test/fixtures/xCartesianTimeParsingOnColors.js
src/index.js|87.0%     54|81.8%    11|    -      0 === test/fixtures/xCartesianTimeParsingOnColors.png
Error: Resource not accessible by integration
```

**Comment by kurkle** [comment]
> [test-*karma] TOTAL: 32 SUCCESS

Its the coverage reporting I added yesterday. Can you remove that from the CI?

**Comment by kurkle** [comment]
That one:

>       - name: Report code coverage
>        uses: zgosalvez/github-actions-report-lcov@v1
>        with:
>          coverage-files: coverage/chrome/lcov.info
>          minimum-coverage: 80
>          artifact-name: code-coverage-report
>          github-token: ${{ secrets.GITHUB_TOKEN }}

**Comment by stockiNail** [comment]
> > [test-*karma] TOTAL: 32 SUCCESS
> 
> Its the coverage reporting I added yesterday. Can you remove that from the CI?

yes I can. Does it mean that we don't test the coverage?

**Comment by stockiNail** [comment]
If you agree, I have got another couple of tests to do and we could check if it works with this others.

**Comment by kurkle** [comment]
> yes I can. Does it mean that we don't test the coverage?

There are no checks for the coverage. I'll add some other service later to check the coverage as sonar can't be used for it (when pull requests come from forked repositories).

> If you agree, I have got another couple of tests to do and we could check if it works with this others.
> 
> EDIT: I mean tests on missing scale and missing color, without any dates

Sure :)

**Comment by stockiNail** [comment]
> > If you agree, I have got another couple of tests to do and we could check if it works with this others.
> > EDIT: I mean tests on missing scale and missing color, without any dates
> 
> Sure :)

I'm going to submit another PR to test the warning when axis is missing and we will see if it works. Few minutes...

**Pull request merged**
