### PR TITLE
Add KARMA test suite to enable testing

### PR DESCRIPTION
**Pull request by stockiNail**
This PR is adding test suite in order to enable the tests.

The source was `chartjs-plugin-annotation` and maybe something is not "perfect".

What cannot do is to register the plugin globally (try in several ways without any success) therefore in this PR the plugin has been adding in the first test case.

**EDIT:** the global registration was fixed putting it in `beforeAll` hook. Thanks @kurkle

### CODE REVIEW

**Comment by stockiNail** [comment]
> What cannot do is to register the plugin globally (try in several ways without any success) therefore in this PR the plugin has been adding in the first test case.

I had a look to `chartjs-plugin-datalabels` which, like this plugin, doesn't have the auto registration. Nevertheless I wasn't able to enable it globally. :(

**Comment by kurkle** [comment]
Oh, how nice! Than you!

**Comment by kurkle** [comment]
> > What cannot do is to register the plugin globally (try in several ways without any success) therefore in this PR the plugin has been adding in the first test case.
> 
> I had a look to `chartjs-plugin-datalabels` which, like this plugin, doesn't have the auto registration. Nevertheless I wasn't able to enable it globally. :(

Did you try adding a `beforeAll` handler in test/index.js?

**Comment by stockiNail** [comment]
> Oh, how nice! Than you!

ur welcome! I wanted to understand how it works ;)

**Comment by stockiNail** [comment]
> Did you try adding a `beforeAll` handler in test/index.js?

No... only in beforeEach. Let me try

**Comment by stockiNail** [comment]
> Did you try adding a `beforeAll` handler in test/index.js?

And as usual you are right! ;) Fixed!

**Review by kurkle — APPROVED** [review]

**Comment by stockiNail** [comment]
@kurkle I'm going to add some test cases because I'll have a couple of PR and I want to make sure do not destroy anything!

**Comment by kurkle** [comment]
> @kurkle I'm going to add some test cases because I'll have a couple of PR and I want to make sure do not destroy anything!

I tweaked the CI to do coverage analysis on sonar cloud too (and removed windows runner, because I don't know how to do coverage on multiple osses and its slow etc)

So, the quality gate is failing currently because test coverage is too low.. looking forward on your new test cases to fix that! :)

**Comment by stockiNail** [comment]
I'm doing... I have added chartjs-adapter-luxon and luxon as dependencies in order to test also the time axis

**Pull request merged**
