### PR TITLE
Add support to time scale with colorStop option configured with formatted dates

### LINKED ISSUE #15: Time and timeseries scale support by setting formatted dates
At the moment, when the plugin is used in a chart with time or timeseries scale, the value to define the color stop must be configured in UTC (millis). 
Probably this is not really comfortable for the users.

The keys of color object could be parsed (as done in the annotation plugin: https://github.com/chartjs/chartjs-plugin-annotation/blob/master/src/helpers/helpers.chart.js#L13-L22)

### PR DESCRIPTION
**Pull request by stockiNail**
Fix #15.

This PR is enable the feature to use in `color` node color stop as formatted date, leveraging on scale parsing.

Example:

```javascript
gradient: {
  backgroundColor: {
    axis: 'x',
      colors: {
        "05/30/2021": 'green',
        "06/02/2021": 'blue',
        "06/04/2021": 'red'
      }
    }
  }
}
```

Time scale options:
```javascript
scales: {
  x: {
    type: 'time', 
    time: {
      unit: 'day',
      parser: 'MM/dd/yyyy',
    }
  }
}
```
timeGradient

### CODE REVIEW

**Comment by stockiNail** [comment]
let me rebase

**Comment by stockiNail** [comment]
This PR is also enabling the colorStop at relative index on labels for `category` axes.

Instead of using the label, you can use the index of the label adding adjustment, like:

```javascript
gradient: {
  backgroundColor: {
    axis: 'x',
      colors: {
        "0": 'green', // position of label at index 0
        "2.5": 'blue', // position of the label between labels at index 2 and 3
        "8.5": 'red' // position of the label between labels at index 8 and 9
      }
    }
  }
}
```

**Comment by stockiNail** [comment]
@kurkle thank you very much for quick approval and merge. Now I can start working to import the plugin in my lib. ;)

**Comment by kurkle** [comment]
I'll delay the release though, because I'd like to add some docs and samples before that. Maybe call it 1.0 too.

**Comment by stockiNail** [comment]
> I'll delay the release though, 

Take your time. Because I have to develop the java wrappers and do all tests, I'm going to starting working with my fork and the file created locally. I'll change when new version will be published. 

> because I'd like to add some docs and samples before that. 

Even if I'm busy (but luckily I can still work in multi threading...) maybe I can help you somehow. Let me know.

> Maybe call it 1.0 too.

Vote for it!

**Pull request merged**
